  version: '3.8' # pourquoi et d ou ca vient
  services:
  mongodb:
    image: mongo:7.0.8  # pourquoi elle
    restart: always #  si stop redémarre le container avec always
    ports:
     - "8090:27017" # port d entrée aux choix 8090:27017 port de mongodb   
    environment:
       MONGO_INITDB_ROOT_USERNAME: utilisateur
       MONGO_INITDB_ROOT_PASSWORD: motdepasse